# Generated by Django 3.1.4 on 2021-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('birthDate', models.DateTimeField(verbose_name='Date of birth')),
                ('deathDate', models.DateTimeField(verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='LocClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('birthDate', models.DateTimeField(verbose_name='Date of birth')),
                ('deathDate', models.DateTimeField(verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebookId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('releaseDate', models.DateTimeField(verbose_name='Date of publication')),
                ('language', models.CharField(max_length=100)),
                ('downloads', models.IntegerField()),
                ('subject', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='polls.Author')),
                ('locClasses', models.ManyToManyField(to='polls.LocClass')),
                ('translators', models.ManyToManyField(to='polls.Translator')),
            ],
        ),
    ]
